### ISSUE TITLE
PyPi package update

### ISSUE THREAD

**Issue by wernight** [pybrain/pybrain#116]
There seem to have been many changes since 2009 (over [4 years ago](https://pypi.python.org/pypi/PyBrain)). The version number on GitHub is almost the same yet it's probably worth making another release.

PyPi allows installing simply for a user or system and other things. Not that git clone isn't good in many cases.

**Comment by chrisgogreen** [comment]
+1, this would help me. Who is responsible for updating PyPi?

**Comment by schaul** [comment]
Pypi was updated a couple months ago to v0.3.3.
