### ISSUE TITLE
python3.5.2

### ISSUE THREAD

**Issue by hhuhhu** [pybrain/pybrain#222]
Does pybrain support python3.5.2?  The simple 'import pybrain '  abort. like below. I install it just with 'pip install pybrain'
D:\Anaconda3.5.2\python.exe F:/gitProjects/vnpy_future/pre_code/cnn/rnn.py
Traceback (most recent call last):
  File "F:/gitProjects/vnpy_future/pre_code/cnn/rnn.py", line 7, in <module>
    import pybrain
  File "D:\Anaconda3.5.2\lib\site-packages\pybrain\__init__.py", line 1, in <module>
    from structure.__init__ import *
ImportError: No module named 'structure'

**Comment by dannluciano** [comment]
Try this: 
```python
pip install numpy scipy structure sequential https://github.com/pybrain/pybrain/archive/0.3.3.zip
```

**Comment by yemauricio** [comment]
Thanks a lot dannluciano. Pybrain is alive!!!

**Comment by dannluciano** [comment]
^^

**Comment by dannluciano** [comment]
Please close this issue.
